sudo: required
language: generic
services: 
  - docker

before_install: 
  - docker build -t AbdallaSrouji/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true AbdallaSrouji/docker-react npm run test